[package]
name = "display_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
softbuffer = "0.4.1"
toml = "0.8.12"
winit = "0.29.15"
zerocopy = "0.7.32"
